// This file was generated by json2swift. https://github.com/pyckamil/json2swift

import Foundation
import Unbox

// swiftlint:disable identifier_name

public struct Media: Equatable {
    public let m: URL
    public init(m: URL) {
        self.m = m
    }
}

extension Media: Unboxable {
    public init(unboxer: Unboxer) throws {
        self.m = try unboxer.unbox(key: "m")
    }
}

public func == (lhs: Media, rhs: Media) -> Bool {
    return
        lhs.m == rhs.m
}
