// This file was generated by json2swift. https://github.com/pyckamil/json2swift

import Foundation
import Unbox

public struct PhotosPublic: Equatable {
    public let description: String
    public let generator: URL
    public let items: [Item]
    public let link: URL
    public let modified: String
    public let title: String
    public init(description: String, generator: URL, items: [Item], link: URL, modified: String, title: String) {
        self.description = description
        self.generator = generator
        self.items = items
        self.link = link
        self.modified = modified
        self.title = title
    }
}

extension PhotosPublic: Unboxable {
    public init(unboxer: Unboxer) throws {
        self.description = try unboxer.unbox(key: "description")
        self.generator = try unboxer.unbox(key: "generator")
        self.items = try unboxer.unbox(key: "items")
        self.link = try unboxer.unbox(key: "link")
        self.modified = try unboxer.unbox(key: "modified")
        self.title = try unboxer.unbox(key: "title")
    }
}

public func == (lhs: PhotosPublic, rhs: PhotosPublic) -> Bool {
    return
        lhs.description == rhs.description
        && lhs.generator == rhs.generator
        && lhs.items == rhs.items
        && lhs.link == rhs.link
        && lhs.modified == rhs.modified
        && lhs.title == rhs.title
}
